#
#
Summary:	net-acct which work with mySQL 
Summary(pl):	net-acct pracujacy z mySQL
Name:		netacct-mysql
Version:	0.75
Release:	0.2
Epoch:		1
License:	GPL
Group:		Networking/Daemons
Source0:	http://telia.dl.sourceforge.net/sourceforge/netacct-mysql/netacct-mysql-0.75.tar.gz
Patch0:		netacct-mysql-rcd.patch
URL:		http://netacct-mysql.sourceforge.net/
BuildRequires:  mysql-static
BuildRequires:  libpcap-devel
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
Netacct-mySQL is a patched version of net-acct which works with mySQL
database.It is a network traffic monitor which can log traffic generated by
a specific network (incoming/outgoing). In fact it works like sniffer, puts
network interface in PROMISC mode and collects traffic. Now it uses libpcap.

%description -l pl
Netacct-mySQL jest ³atan± wersj± net-acct pracuj±c± z baz± mySQL. 
Jest to demon monitoruj±cy ruch w sieci dla konkretnych sieci. Faktycznie
pracuje on jak sniffer ustawiaj±c urz±dzenie w tryb PROMISC i zczytuj±cy
ruch.

%prep
%setup -q
%patch0 -p1
%build
%configure2_13 \
	--prefix=/usr \
	--sysconfdir=/etc/netacct-mysql
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_sysconfdir}

%{__make} install DESTDIR=$RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT/etc/rc.d/init.d/
cp contrib/nacctd.redhat $RPM_BUILD_ROOT/etc/rc.d/init.d/netacct-mysql
%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%attr(750,root,root) %{_sbindir}/*
%attr(750,root,root) /etc/rc.d/init.d/*
%attr(644,root,root) %config(noreplace) %verify(not md5 size mtime) %{_sysconfdir}/netacct-mysql/*
%doc {FAQ,INSTALL,COPYING,CHANGES,README,README.upgrade,TODO,contrib} 

%{_mandir}/man8/*
