Summary:	net-acct which work with MySQL 
Summary(pl):	net-acct pracuj±cy z MySQL
Name:		netacct-mysql
Version:	0.75
Release:	0.2
Epoch:		1
License:	GPL
Group:		Networking/Daemons
Source0:	http://dl.sourceforge.net/netacct-mysql/netacct-mysql-0.75.tar.gz
Patch0:		%{name}-rcd.patch
Patch1:		%{name}-shared.patch
URL:		http://netacct-mysql.sourceforge.net/
BuildRequires:	autoconf
BuildRequires:	automake
BuildRequires:  libpcap-devel
BuildRequires:  mysql-devel
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%define		_sysconfdir	/etc/netacct-mysql

%description
Netacct-MySQL is a patched version of net-acct which works with MySQL
database. It is a network traffic monitor which can log traffic
generated by a specific network (incoming/outgoing). In fact it works
like sniffer, puts network interface in PROMISC mode and collects
traffic. Now it uses libpcap.

%description -l pl
Netacct-MySQL jest ³atan± wersj± net-acct pracuj±c± z baz± danych
MySQL. Jest to demon monitoruj±cy ruch w sieci dla konkretnych sieci.
Faktycznie pracuje on jak sniffer ustawiaj±c urz±dzenie w tryb PROMISC
i zczytuj±cy ruch.

%prep
%setup -q
%patch0 -p1
%patch1 -p1

%build
%{__aclocal}
%{__autoconf}
%{__automake}
%configure

%{__make}

%install
rm -rf $RPM_BUILD_ROOT
install -d $RPM_BUILD_ROOT%{_sysconfdir}

%{__make} install DESTDIR=$RPM_BUILD_ROOT

install -d $RPM_BUILD_ROOT/etc/rc.d/init.d
install contrib/nacctd.redhat $RPM_BUILD_ROOT/etc/rc.d/init.d/netacct-mysql

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(644,root,root,755)
%doc FAQ INSTALL CHANGES README README.upgrade TODO contrib/{mrta2netacct,nacctp*,upgrade*}
%attr(750,root,root) %{_sbindir}/*
%attr(754,root,root) /etc/rc.d/init.d/*
%dir %{_sysconfdir}
%attr(644,root,root) %config(noreplace) %verify(not md5 size mtime) %{_sysconfdir}/*
%{_mandir}/man8/*
